### ISSUE TITLE
Can't get example to work

### ISSUE THREAD

**Issue by Kottakji** [polleverywhere/chaperon#18]
I've tried following the tutorial, but can't get it working. Am I forgetting something?

Here is the error message + setup:

```bash
iex(1)> Chaperon.run_load_test(CVA.LoadTest)

09:06:47.609 [error] 22df804b-580b-4a18-b5e8-e3cf9e55f7f3 CVA.Scenario | Failed to connect via WS to wss://echo.websocket.org/ - Connection closed remotely 
 
09:06:47.612 [error] Task #PID<0.358.0> started from #PID<0.359.0> terminating
** (CaseClauseError) no case clause matching: %Chaperon.Session{assigned: %{counter: 0}, async_tasks: %{}, cancellation: nil, config: %{base_url: "wss://echo.websocket.org", echo: %{iterations: 10}, merge_scenario_sessions: true, metrics: nil}, cookies: [], errors: %{}, id: "22df804b-580b-4a18-b5e8-e3cf9e55f7f3", interval_task: nil, metrics: %{}, name: "CVA.Scenario", parent_id: nil, parent_pid: nil, results: %{}, scenario: %Chaperon.Scenario{module: CVA.Scenario}, timeout_at: nil}
    (chaperon 0.3.1) lib/chaperon/session.ex:648: Chaperon.Session.run_action/2
    (chaperon_vote_api 0.1.0) lib/scenario.ex:14: CVA.Scenario.run/1
    (chaperon 0.3.1) lib/chaperon/scenario.ex:198: Chaperon.Scenario.with_scenario/3
    (chaperon 0.3.1) lib/chaperon/scenario.ex:172: Chaperon.Scenario.run/2
    (chaperon 0.3.1) lib/chaperon/scenario.ex:122: Chaperon.Scenario.execute/2
    (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Chaperon.Scenario.execute/2
    Args: [CVA.Scenario, %{base_url: "wss://echo.websocket.org", echo: %{iterations: 10}, merge_scenario_sessions: true, metrics: nil}]
** (EXIT from #PID<0.353.0>) shell process exited with reason: an exception was raised:
    ** (CaseClauseError) no case clause matching: %Chaperon.Session{assigned: %{counter: 0}, async_tasks: %{}, cancellation: nil, config: %{base_url: "wss://echo.websocket.org", echo: %{iterations: 10}, merge_scenario_sessions: true, metrics: nil}, cookies: [], errors: %{}, id: "22df804b-580b-4a18-b5e8-e3cf9e55f7f3", interval_task: nil, metrics: %{}, name: "CVA.Scenario", parent_id: nil, parent_pid: nil, results: %{}, scenario: %Chaperon.Scenario{module: CVA.Scenario}, timeout_at: nil}
        (chaperon 0.3.1) lib/chaperon/session.ex:648: Chaperon.Session.run_action/2
        (chaperon_vote_api 0.1.0) lib/scenario.ex:14: CVA.Scenario.run/1
        (chaperon 0.3.1) lib/chaperon/scenario.ex:198: Chaperon.Scenario.with_scenario/3
        (chaperon 0.3.1) lib/chaperon/scenario.ex:172: Chaperon.Scenario.run/2
        (chaperon 0.3.1) lib/chaperon/scenario.ex:122: Chaperon.Scenario.execute/2
        (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
        (elixir 1.10.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
        (stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

```elixir
defmodule CVA.LoadTest do
  use Chaperon.LoadTest
  
  def default_config,
      do: %{
        base_url: "wss://echo.websocket.org",
        merge_scenario_sessions: true
      }
  
  def scenarios,
      do: [
        {{1, CVA.Scenario},
          %{
            echo: %{
              iterations: 10
            }
          }}
      ]
end
```

```elixir
defmodule CVA.Scenario do
  use Chaperon.Scenario
  
  def init(session) do
    session
    |> assign(counter: 0)
    |> ok
  end
  
  def run(session) do
    iterations = session |> config([:echo, :iterations])
    
    session
    |> ws_connect("/")
    |> repeat_traced(:echo, iterations)
    |> log_info("Echo finished after #{iterations} iterations")
    |> ws_close
  end
  
  def echo(session) do
    msg = "Echo ##{session.assigned.counter}"
    
    session
    |> ws_send(msg)
    |> ws_await_recv(msg)
    |> update_assign(counter: &(&1 + 1))
  end
end
```

**Comment by bakkdoor** [comment]
Sorry for the late reply, just noticed this issue now. In case you are still running into this issue: Based on the first log line 
`09:06:47.609 [error] 22df804b-580b-4a18-b5e8-e3cf9e55f7f3 CVA.Scenario | Failed to connect via WS to wss://echo.websocket.org/ - Connection closed remotely` it looks like your are being throttled by echo.websocket.org's servers and connections are bring closed because you are spamming them with your load tests ;) 
Maybe try hitting a web server you own? If you run the load test too often against their servers they will start closing connections from your IP.
